#TinySimHash周りの設定
simhash_path: /Users/y_benjo/TinySimHash
fserver_port: 90001
hserver_port: 90002
k: 3
l: 10
related_size: 5

#データベース周りの設定
#主に access_db.rbで使用
localhost: 127.0.0.1
word_id_port: 9998
id_word_port: 9996
journal_port: 9999
mutual_info_port: 9997
impact_factor_port: 9995
